modLoader="javafml"
loaderVersion="[4,)" # NeoForge 21.x
license="MIT"

[[mods]]
modId="shopandeconomy"
version="${file.jarVersion}"
displayName="Shop & Economy"
authors="You"
description="Simple shop & economy mod for 1.21.1 (NeoForge)."

[[dependencies.shopandeconomy]]
modId="neoforge"
type="required"
versionRange="[21.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.shopandeconomy]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"
